name: Publish Image

on:
    push:
        tags:
            - 'v[0-9]+.*'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Publish
            uses: HurricanKai/Publish-Docker-Github-Action@master
            if: contains(github.ref, 'refs/tags/')
            with:
              name: monolithprojects/systemd-fedora39
              username: monolithprojects
              password: ${{ secrets.TOKEN }}
              tagging: true
              registry: docker.io
              dockerfile: Dockerfile
